In [5]:
import sqlite3
import pandas
from sqlalchemy import create_engine

conn = sqlite3.connect('citydata.db')

In [8]:
engine = create_engine('sqlite:///citydata.db')

df = pandas.read_sql_table('UZAs', engine)

dependent_data = df[["AA Urbanized Area (UZA) Name", "Public Transit Percent", "Per Capita Transit Passenger Miles / yr", "Per Capita Congestion Delay hrs/yr- calc", "Transport Expenditures, Percent of Total Income", "Travel to Work - Public Transit Percent"]]

dependent_data

,AA Urbanized Area (UZA) Name,Public Transit Percent,Per Capita Transit Passenger Miles / yr,Per Capita Congestion Delay hrs/yr- calc,"Transport Expenditures, Percent of Total Income",Travel to Work - Public Transit Percent
0,"New York-Newark, NY-NJ-CT",0.311,1179.5,21.6,0.11,31.1
1,"Los Angeles-Long Beach-Santa Ana, CA",0.063,260.8,39.1,0.13,6.3
2,"Chicago, IL-IN",0.126,447.8,24.9,0.12,12.6
3,"Philadelphia, PA-NJ-DE-MD",0.099,302.5,21.1,0.11,9.9
4,"Miami, FL",0.037,179.3,28.2,0.14,3.7
...,...,...,...,...,...,...
75,"Columbia, SC",0.010,26.1,8.5,NaN,1.0
76,"Knoxville, TN",0.006,25.2,NaN,NaN,0.6
77,"Youngstown, OH-PA",0.006,14.4,NaN,NaN,0.6
78,"Syracuse, NY",0.028,97.8,NaN,NaN,2.8
79,"Bakersfield, CA",0.016,54.4,7.4,NaN,1.6

In [11]:
dont_fill = dependent_data.columns.difference(['AA Urbanized Area (UZA) Name'])
dependent_data[dont_fill] = dependent_data[dont_fill].fillna(dependent_data[dont_fill].mean())

dependent_data

/tmp/ipykernel_79685/4170521839.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dependent_data[dont_fill] = dependent_data[dont_fill].fillna(dependent_data[dont_fill].mean())

,AA Urbanized Area (UZA) Name,Public Transit Percent,Per Capita Transit Passenger Miles / yr,Per Capita Congestion Delay hrs/yr- calc,"Transport Expenditures, Percent of Total Income",Travel to Work - Public Transit Percent
0,"New York-Newark, NY-NJ-CT",0.311,1179.5,21.600000,0.110000,31.1
1,"Los Angeles-Long Beach-Santa Ana, CA",0.063,260.8,39.100000,0.130000,6.3
2,"Chicago, IL-IN",0.126,447.8,24.900000,0.120000,12.6
3,"Philadelphia, PA-NJ-DE-MD",0.099,302.5,21.100000,0.110000,9.9
4,"Miami, FL",0.037,179.3,28.200000,0.140000,3.7
...,...,...,...,...,...,...
75,"Columbia, SC",0.010,26.1,8.500000,0.128333,1.0
76,"Knoxville, TN",0.006,25.2,18.572222,0.128333,0.6
77,"Youngstown, OH-PA",0.006,14.4,18.572222,0.128333,0.6
78,"Syracuse, NY",0.028,97.8,18.572222,0.128333,2.8
79,"Bakersfield, CA",0.016,54.4,7.400000,0.128333,1.6

In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

exclude_names = dependent_data.copy()
exclude_names = exclude_names.drop(columns=['AA Urbanized Area (UZA) Name'])
z_scores = pandas.DataFrame()

for col in exclude_names.columns:
    col_zscore = scaler.fit_transform(exclude_names[[col]])
    z_scores[f'{col}_ZScore'] = col_zscore.flatten()

z_scores

,Public Transit Percent_ZScore,Per Capita Transit Passenger Miles / yr_ZScore,Per Capita Congestion Delay hrs/yr- calc_ZScore,"Transport Expenditures, Percent of Total Income_ZScore",Travel to Work - Public Transit Percent_ZScore
0,5.994290,5.744247,3.867449e-01,-1.652222,6.012313
1,0.518086,0.663285,2.622059e+00,0.150202,0.509499
2,1.909219,1.697507,8.082613e-01,-0.751010,1.907391
3,1.313019,0.893911,3.228787e-01,-1.652222,1.308295
4,-0.056032,0.212541,1.229778e+00,1.051414,-0.067409
...,...,...,...,...,...
75,-0.652231,-0.634747,-1.286548e+00,0.000000,-0.666506
76,-0.740557,-0.639725,-4.537961e-16,0.000000,-0.755261
77,-0.740557,-0.699455,-4.537961e-16,0.000000,-0.755261
78,-0.254765,-0.238203,-4.537961e-16,0.000000,-0.267108
79,-0.519743,-0.478231,-1.427053e+00,0.000000,-0.533373

In [22]:
z_scores['Transit Score'] = z_scores.sum(axis=1)

z_scores

,Public Transit Percent_ZScore,Per Capita Transit Passenger Miles / yr_ZScore,Per Capita Congestion Delay hrs/yr- calc_ZScore,"Transport Expenditures, Percent of Total Income_ZScore",Travel to Work - Public Transit Percent_ZScore,Transit Score
0,5.994290,5.744247,3.867449e-01,-1.652222,6.012313,16.485374
1,0.518086,0.663285,2.622059e+00,0.150202,0.509499,4.463132
2,1.909219,1.697507,8.082613e-01,-0.751010,1.907391,5.571369
3,1.313019,0.893911,3.228787e-01,-1.652222,1.308295,2.185882
4,-0.056032,0.212541,1.229778e+00,1.051414,-0.067409,2.370292
...,...,...,...,...,...,...
75,-0.652231,-0.634747,-1.286548e+00,0.000000,-0.666506,-3.240032
76,-0.740557,-0.639725,-4.537961e-16,0.000000,-0.755261,-2.135542
77,-0.740557,-0.699455,-4.537961e-16,0.000000,-0.755261,-2.195273
78,-0.254765,-0.238203,-4.537961e-16,0.000000,-0.267108,-0.760076
79,-0.519743,-0.478231,-1.427053e+00,0.000000,-0.533373,-2.958400

In [23]:
dependent_data_total = pandas.concat([dependent_data, z_scores], axis=1)

dependent_data_total

,AA Urbanized Area (UZA) Name,Public Transit Percent,Per Capita Transit Passenger Miles / yr,Per Capita Congestion Delay hrs/yr- calc,"Transport Expenditures, Percent of Total Income",Travel to Work - Public Transit Percent,Public Transit Percent_ZScore,Per Capita Transit Passenger Miles / yr_ZScore,Per Capita Congestion Delay hrs/yr- calc_ZScore,"Transport Expenditures, Percent of Total Income_ZScore",Travel to Work - Public Transit Percent_ZScore,Transit Score
0,"New York-Newark, NY-NJ-CT",0.311,1179.5,21.600000,0.110000,31.1,5.994290,5.744247,3.867449e-01,-1.652222,6.012313,16.485374
1,"Los Angeles-Long Beach-Santa Ana, CA",0.063,260.8,39.100000,0.130000,6.3,0.518086,0.663285,2.622059e+00,0.150202,0.509499,4.463132
2,"Chicago, IL-IN",0.126,447.8,24.900000,0.120000,12.6,1.909219,1.697507,8.082613e-01,-0.751010,1.907391,5.571369
3,"Philadelphia, PA-NJ-DE-MD",0.099,302.5,21.100000,0.110000,9.9,1.313019,0.893911,3.228787e-01,-1.652222,1.308295,2.185882
4,"Miami, FL",0.037,179.3,28.200000,0.140000,3.7,-0.056032,0.212541,1.229778e+00,1.051414,-0.067409,2.370292
...,...,...,...,...,...,...,...,...,...,...,...,...
75,"Columbia, SC",0.010,26.1,8.500000,0.128333,1.0,-0.652231,-0.634747,-1.286548e+00,0.000000,-0.666506,-3.240032
76,"Knoxville, TN",0.006,25.2,18.572222,0.128333,0.6,-0.740557,-0.639725,-4.537961e-16,0.000000,-0.755261,-2.135542
77,"Youngstown, OH-PA",0.006,14.4,18.572222,0.128333,0.6,-0.740557,-0.699455,-4.537961e-16,0.000000,-0.755261,-2.195273
78,"Syracuse, NY",0.028,97.8,18.572222,0.128333,2.8,-0.254765,-0.238203,-4.537961e-16,0.000000,-0.267108,-0.760076
79,"Bakersfield, CA",0.016,54.4,7.400000,0.128333,1.6,-0.519743,-0.478231,-1.427053e+00,0.000000,-0.533373,-2.958400

In [25]:
transit_scores = dependent_data_total[['AA Urbanized Area (UZA) Name', 'Transit Score']]

transit_scores

            AA Urbanized Area (UZA) Name  Transit Score
0              New York-Newark, NY-NJ-CT      16.485374
1   Los Angeles-Long Beach-Santa Ana, CA       4.463132
2                         Chicago, IL-IN       5.571369
3              Philadelphia, PA-NJ-DE-MD       2.185882
4                              Miami, FL       2.370292
..                                   ...            ...
75                          Columbia, SC      -3.240032
76                         Knoxville, TN      -2.135542
77                     Youngstown, OH-PA      -2.195273
78                          Syracuse, NY      -0.760076
79                       Bakersfield, CA      -2.958400

[80 rows x 2 columns]

In [26]:
merged_df = pandas.merge(transit_scores, df, on='AA Urbanized Area (UZA) Name', how='inner')

In [27]:
merged_df.to_sql('uza_table', conn, if_exists='replace', index=False)

conn.commit()
conn.close()